-- Parent-support ticketing + intro chatbot — schema for PostgreSQL.
-- Generated by /design-system. Source of truth: .claude/rules/db-schema.md — never
-- edit this file's table shapes without updating that rule first.
-- Table order follows FK dependencies: students, staff → parents, tickets → faq, leads, unanswered.

-- === Domain tables (from the brief) ===

CREATE TABLE students (
  id            SERIAL PRIMARY KEY,
  name          TEXT NOT NULL,
  grade         TEXT NOT NULL,
  class         TEXT NOT NULL,
  parent_phone  TEXT NOT NULL,
  unique_code   TEXT NOT NULL UNIQUE
);

CREATE TABLE staff (
  id        SERIAL PRIMARY KEY,
  name      TEXT NOT NULL,
  chat_id   BIGINT NOT NULL UNIQUE,
  category  TEXT NOT NULL
);

CREATE TABLE parents (
  id            SERIAL PRIMARY KEY,
  student_id    INTEGER NOT NULL REFERENCES students(id),
  chat_id       BIGINT NOT NULL UNIQUE,
  verified_at   TIMESTAMPTZ
);

CREATE TABLE tickets (
  id              SERIAL PRIMARY KEY,
  student_id      INTEGER NOT NULL REFERENCES students(id),
  category        TEXT NOT NULL,
  body            TEXT NOT NULL,
  status          TEXT NOT NULL DEFAULT 'باز',
  assignee_id     INTEGER REFERENCES staff(id),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  first_reply_at  TIMESTAMPTZ,
  closed_at       TIMESTAMPTZ,
  rating          SMALLINT,
  update_id       BIGINT UNIQUE
);

CREATE TABLE faq (
  id         SERIAL PRIMARY KEY,
  keywords   TEXT NOT NULL,
  answer     TEXT NOT NULL,
  menu_path  TEXT NOT NULL
);

CREATE TABLE leads (
  id          SERIAL PRIMARY KEY,
  phone       TEXT NOT NULL,
  question    TEXT NOT NULL,
  source      TEXT NOT NULL DEFAULT 'ربات معرفی',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE unanswered (
  id          SERIAL PRIMARY KEY,
  chat_id     BIGINT NOT NULL,
  text        TEXT NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- === Operational tables (documented additions, see db-schema.md "Operational tables") ===

CREATE TABLE bot_offset (
  bot_name        TEXT PRIMARY KEY,
  last_update_id  BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE verification_attempts (
  chat_id          BIGINT PRIMARY KEY,
  attempt_count    SMALLINT NOT NULL DEFAULT 0,
  last_attempt_at  TIMESTAMPTZ
);

CREATE TABLE sla_alerts (
  id         SERIAL PRIMARY KEY,
  ticket_id  INTEGER NOT NULL REFERENCES tickets(id),
  kind       TEXT NOT NULL,
  sent_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (ticket_id, kind)
);

CREATE TABLE error_log (
  id           SERIAL PRIMARY KEY,
  workflow     TEXT NOT NULL,
  node_name    TEXT NOT NULL,
  message      TEXT NOT NULL,
  chat_id      BIGINT,
  occurred_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- === Indexes ===

CREATE INDEX idx_parents_chat_id       ON parents(chat_id);
CREATE INDEX idx_tickets_student_id    ON tickets(student_id);
CREATE INDEX idx_tickets_status        ON tickets(status);
CREATE INDEX idx_tickets_assignee_id   ON tickets(assignee_id);
CREATE INDEX idx_staff_category        ON staff(category);
CREATE INDEX idx_students_unique_code  ON students(unique_code);
CREATE INDEX idx_sla_alerts_ticket_id  ON sla_alerts(ticket_id);
